version: '3'

services:
  phpwd:
    build: .
    volumes:
      - .:/tmp
    depends_on:
      - selenium-chrome

  selenium-chrome:
    image: selenium/standalone-chrome-debug:3
    ports:
      - 4444:4444
      - 5900:5900
